<?php

function shift_cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Shift Cipher Encryption',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_output'] = array(
        'title' => 'Cipher Output',
        'page callback' => 'shift_cipher_output',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['magnitude'] = array(
        '#title' => 'Shift Magnitude',
        '#type' => 'textfield',
        '#description' => t('Enter the number of letters to shift by'),
        '#element_validate' => array(
            'element_validate_integer_positive',
            'element_validate_within_25'),
        );
    $form['direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'radios',
        '#default_value' => 'right',
        '#options' => array(
            'left' => t('left'),
            'right' => t('right'),
        ),
    );
    $form['phrase'] = array(
        '#title' => 'Input Phrase',
        '#type' => 'textfield',
        '#description' => t('Enter the phrase to encrypt'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}

function element_validate_within_25($element) {
    if($element['#value'] > 25 || $element['#value'] < 1) {
        form_error($element, t('Shift magnitude must be between 1 and 25'));
    }
}

function shift_cipher_form_submit($form, &$form_state) {
    $magnitude = $form_state['values']['magnitude'];
    $direction = $form_state['values']['direction'];
    $input_phrase = $form_state['values']['phrase'];

    if($direction == 'left') {
        $magnitude = 26 - $magnitude;
    }

    $phrase = str_split(strtolower($input_phrase));

    $alphabet = range('a', 'z');

    $output_phrase = '';

    foreach($phrase as $element) {
        if(in_array($element, $alphabet)) {
            $index_of_letter = array_search($element, $alphabet);
            $encrypted_letter_index = ($index_of_letter + $magnitude) % 26;
            $output_phrase .= $alphabet[$encrypted_letter_index];
        }
        else {
            $output_phrase .= $element;
        }
    }

    $_SESSION['encrypted_phrase'] = $output_phrase;
    $form_state['redirect'] = 'cipher_output';
}

function shift_cipher_output() {
    return '<p>Shift cipher output: ' . $_SESSION['encrypted_phrase'] . '</p>';
}
