<?php

function shift_cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Shift Cipher Encryption',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_output'] = array(
        'title' => 'Cipher Output',
        'page callback' => 'shift_cipher_output',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function shift_cipher_form() {
    $form['magnitude'] = array(
        '#title' => 'Shift Magnitude',
        '#type' => 'textfield',
        '#description' => t('Enter the number of letters to shift by'),
    );
    $form['direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'radios',
        '#options' => array(
            'left' => t('left'),
            'right' => t('right'),
        ),
    );
    $form['phrase'] = array(
        '#title' => 'Input Phrase',
        '#type' => 'textfield',
        '#description' => t('Enter the phrase to encrypt'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );
    return $form;
}

function shift_cipher_form_submit($form, &$form_state) {
    $magnitude = $form_state['values']['magnitude'];
    $direction = $form_state['values']['direction'];
    $input_phrase = $form_state['values']['phrase'];


    $_SESSION['encrypted_phrase'] = $input_phrase;
    $form_state['redirect'] = 'cipher_output';
}

function shift_cipher_output() {
    return '<p>Shift cipher output:' . $_SESSION['encrypted_phrase'] . '</p>';
}
